version: "3.8" # Specifying a version is good practice

services:
  haxball-server:
    image: "register.kacpersledz.com/hax-server:0.1.0"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - WS_PATH=${WS_PATH}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
    ports:
      - "5010:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
